title = "The Mind of John"
author = "Brennan"
#copyright = "2020-2021"
description = "The Mind of John"
keywords = ""
mainSections = ["post"]
doNotLoadAnimations = false
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/brennan-mcdonald"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/brennanmcdonald"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/brennanmcd"